FROM nginx

COPY <<EOF /etc/nginx/nginx.conf
events {}

http {
    server {
        listen *:8000;

        location / {
          proxy_pass http://localhost:8080;
        }

        location /auth/ {
          proxy_pass http://localhost:3001/;
        }

        location /attachments/ {
          proxy_pass http://localhost:4567/;
        }

        location /passphrase {
          proxy_pass http://localhost:4000;
        }
    }
}
EOF
