[package]
name = "fragment-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
awc = "3.5.0"
env_logger = "0.11.3"
log = "0.4.21"
mime = "0.3.17"
serde = { version = "1.0.202", features = ["derive"] }
