name: "Build & Push Container Images"
on:
  push:
    branches: ["main"]

env:
  IMAGE_REPO: ghcr.io/${{ github.repository }}

jobs:
  build-and-push-server:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Build & push frontend image
        id: build
        env:
          REGISTRY_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # provenance attestation action only looks in default docker config location :(
          # https://github.com/sigstore/sigstore-js/blob/554f3cd250f80e373e777f617cad3fa387c674b1/packages/oci/src/credentials.ts#L34
          echo "$GITHUB_TOKEN" | docker login -u "$REGISTRY_USER" --password-stdin ghcr.io

          # I can't just use --digestfile "$GITHUB_OUTPUT" since that'll truncate it which I think is bad? docs are unclear as to whether $GITHUB_OUTPUT is shared
          $(nix build --print-out-paths ".#fragment-server-image") | gzip --fast | skopeo copy docker-archive:/dev/stdin "docker://${IMAGE_REPO}:server" --digestfile "$RUNNER_TEMP/digest"
          echo "digest=$(<${RUNNER_TEMP}/digest)" >> "$GITHUB_OUTPUT"

      - name: Generate provenance attestation
        uses: actions/attest-build-provenance@v1.1.0
        with:
          subject-name: ${{ env.IMAGE_REPO }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
        
