name: "Build & Push Container Images"
on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v26

      - name: Build & Push Frontend Image
        env:
          REGISTRY_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $(nix build --print-out-paths ".?submodules=1#frontend-image") | gzip --fast | skopeo copy --dest-creds "$REGISTRY_USER:$GITHUB_TOKEN" docker-archive:/dev/stdin "docker://${REGISTRY}/${IMAGE_REPO}:frontend"
